### ISSUE TITLE
Error installing using Hubitat Package Manager

### ISSUE THREAD

**Issue by agentorange96** [rvrolyk/SleepNumberController#20]
I am unable to install this app on my Hubitat C8. There doesn't appear to be much information of value here, but this is what I do have.

Error:
`Error Occurred During Installation
An error occurred while installing the package: Failed to install app https://raw.githubusercontent.com/rvrolyk/SleepNumberController/master/SleepNumberController_App.groovy. Please notify the package developer..`

Hubitat Logs:
`app:672024-10-30 08:12:58.944 AMinfoFatal error occurred, rolling back
app:672024-10-30 08:12:58.290 AMinfoInstalling Sleep Number Controller
app:672024-10-30 08:12:57.944 AMinfoDownloading Sleep Number Bed
app:672024-10-30 08:12:57.517 AMinfoDownloading Sleep Number Controller
app:672024-10-30 08:12:57.281 AMdebugInstall beginning
app:672024-10-30 08:12:57.278 AMdebugprefInstall
app:672024-10-30 08:12:54.389 AMdebugprefInstallVerify`

**Comment by rvrolyk** [comment]
This seems to be more an HPM thing than a problem with this app; a few folks have seen this but it's pretty rare.  See the community thread here https://community.hubitat.com/t/release-sleep-number-controller-control-your-sleep-number-bed-and-use-it-for-presence/46454/577?u=rvrolyk

**Comment by agentorange96** [comment]
I can confirm that manually installing the library worked. Do we know if the HPM just is unable to install libraries or something? Anyway, thank you both for the help here and for your work to create this to begin with!
